# Generated by Django 5.1.6 on 2025-03-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('manufacturer', models.CharField(max_length=120)),
                ('country_manufacturer', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('available', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=12000)),
                ('description_block', models.CharField(max_length=12000)),
                ('charge_block', models.CharField(max_length=120)),
                ('control_range', models.CharField(max_length=120)),
                ('max_load', models.CharField(max_length=120)),
                ('type_connection', models.CharField(max_length=120)),
                ('type_device', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Thermostats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='BuyCertificate',
        ),
        migrations.DeleteModel(
            name='BuySkiPass',
        ),
        migrations.DeleteModel(
            name='ReplenishmentOfBalanceSkiPass',
        ),
        migrations.AddField(
            model_name='thermostat',
            name='thermostat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermostat', to='HeatMaster.thermostats'),
        ),
    ]
