# Generated by Django 5.1.6 on 2025-03-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0002_thermostat_thermostats_delete_buycertificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottageimage',
            name='cottage',
        ),
        migrations.RemoveField(
            model_name='peoplereservationcottage',
            name='cottage',
        ),
        migrations.RemoveField(
            model_name='servicesimage',
            name='service',
        ),
        migrations.RemoveField(
            model_name='peoplereservationinstructor',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='peoplereservationinstrument',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='posterimage',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='roadsimage',
            name='roads',
        ),
        migrations.DeleteModel(
            name='Cottage',
        ),
        migrations.DeleteModel(
            name='CottageImage',
        ),
        migrations.DeleteModel(
            name='CottageReservation',
        ),
        migrations.DeleteModel(
            name='PeopleReservationCottage',
        ),
        migrations.DeleteModel(
            name='OurServices',
        ),
        migrations.DeleteModel(
            name='ServicesImage',
        ),
        migrations.DeleteModel(
            name='PeopleReservationInstructor',
        ),
        migrations.DeleteModel(
            name='ReservationInstructor',
        ),
        migrations.DeleteModel(
            name='PeopleReservationInstrument',
        ),
        migrations.DeleteModel(
            name='ReservationInstrument',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.DeleteModel(
            name='PosterImage',
        ),
        migrations.DeleteModel(
            name='Roads',
        ),
        migrations.DeleteModel(
            name='RoadsImage',
        ),
    ]
