# Generated by Django 5.1.6 on 2025-03-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0003_remove_cottageimage_cottage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=120)),
                ('text', models.TextField(max_length=1000)),
                ('text_two', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('procedure', models.CharField(max_length=120)),
                ('stage', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('produce', models.CharField(max_length=120)),
                ('type_across', models.CharField(max_length=120)),
                ('install', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('history', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HeatedMats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('fullname', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('operator', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HotCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LetsCooperate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=120)),
                ('operator', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MethodPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1000)),
                ('date_work', models.DateField()),
                ('sphere', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WarmFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=120)),
                ('history', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='thermostat',
            old_name='thermostat',
            new_name='thermostats',
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='price',
            field=models.FloatField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('part', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='HeatMaster.historyapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(max_length=120)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blod', to='HeatMaster.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='HeatMaster.blog')),
            ],
        ),
        migrations.CreateModel(
            name='ThermostatImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thermostat_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermostat', to='HeatMaster.thermostat')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('length', models.IntegerField()),
                ('power', models.CharField(max_length=120)),
                ('price', models.FloatField(max_length=1000)),
                ('model_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warm_floor', to='HeatMaster.warmfloor')),
            ],
        ),
    ]
