# Generated by Django 5.1.6 on 2025-03-22 23:06

import HeatMaster.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0004_blog_calculateprice_heatedmats_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='application',
        ),
        migrations.AddField(
            model_name='historyapplication',
            name='application',
            field=models.ForeignKey(default=HeatMaster.models.get_default_application, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='HeatMaster.applications'),
        ),
    ]
