# Generated by Django 5.1.6 on 2025-03-23 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0006_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='final',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='blog',
            name='start',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_two',
            field=models.TextField(max_length=10000),
        ),
    ]
