# Generated by Django 5.1.6 on 2025-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0007_blog_date_blog_final_blog_start_alter_blog_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='date_work',
            field=models.CharField(max_length=10),
        ),
    ]
