# Generated by Django 5.2.6 on 2025-10-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0009_alter_thermostat_available_cart_order_orderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermostatComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thermostat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HeatMaster.thermostat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermostat_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
