# Generated by Django 5.2.8 on 2025-12-01 09:50

from django.db import migrations

def create_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Manager')

class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0010_thermostatcomment'),
    ]

    operations = [
        migrations.RunPython(create_manager_group),
    ]
