# Generated by Django 5.2.8 on 2025-12-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMaster', '0011_create_manager_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='include_installation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='include_installation',
            field=models.BooleanField(default=False),
        ),
    ]
